title: Code Lola Code!
description: > # this means to ignore newlines until "baseurl:"
   I'm a Computer Engineer, passionate about Mobile, Web and Cloud Applications development.</br>Always interested in new technologies and learning new stuff.</br>Any thing about women in tech, football, spaceships and dogs catches my eye.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Parima Ayazi # add your name
author-img: parima-ayazi.jpg # add your photo
about-author: I'm a Computer Engineer, passionate about Mobile, Web and Cloud Applications development.</br>Always interested in new technologies and learning new stuff.</br>Any thing about women in tech, football, spaceships and dogs catches my eye.  # add description
social-twitter: parimaayazi # add your Twitter handle
social-instagram: codelolacode # add your Instagram handle
social-github: parimaay # add your Github handle
social-linkedin: parima-ayazi-7a5871a4 # add your Linkedin handle
social-email: parimaayazi@gmail.com # add your Email address
google-site-verification: s5uwUqn-pX6x2OFm0BGT0yVk-qWofdYbVs5qWV-mRoM
analytics:
  		provider: "google-universal"
  	google:
 	tracking_id: "UA-123172945-1"


# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
